---
driver:
  name: vagrant

driver_config:
  require_chef_omnibus: true

provisioner:
  name: chef_zero
  data_bags_path: 'test/integration/data_bags'
  encrypted_data_bag_secret_key_path: 'test/integration/encrypted_data_bag_secret'
  environments_path: 'test/integration/environments'
  require_chef_omnibus: '11.16.4'
  client_rb:
    environment: 'dev'
  attributes:
    omnibus_updater:
      force_latest: false
      version:      11.16.4
    public_info:
      remote_ip: '127.0.0.1'
    openssh:
      server:
        password_authentication: 'yes'
        permit_root_login: 'yes'
    ntp:
      apparmor_enabled: false
    cloud:
      public_ipv4: '127.0.0.1'
    authorization:
      sudo:
        users: ['vagrant','kitchen']
        passwordless: true
    platformstack:
      cloud_backup:
        enabled: false
      cloud_monitoring:
        enabled: false
      omnibus_updater:
        enabled: false
      iptables:
        allow_ssh_from_world: true
    rackspace:
      cloud_credentials:
        username: 'racker'
        api_key: 'sekrit'
    disk:
      timeout: 10
    testkitchen: true
    mysql:
      server_root_password: 'mysql_test'
      master: '127.0.0.1'
    network:
      interfaces:
        eth1:
          addresses:
            127.0.0.1:
              family: 'inet'

platforms:
  - name: ubuntu-14.04

suites:
  - name: app_and_db
    run_list:
      - recipe[1722773-latina-media-ventures::role_app]
      - recipe[1722773-latina-media-ventures::role_db_galera]
